# Generated by Django 2.2.6 on 2019-11-18 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('marca', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Reebok', 'Reebok')], max_length=50, null=True)),
                ('talla', models.CharField(choices=[('40','40'), ('40.5', '40.5'), ('41', '41'), ('41.5', '41.5'), ('42', '42'), ('42.5', '42,5'), ('43', '43'), ('43.5', '43.5'), ('44', '44')], max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('Deportivas', 'Deportivas'), ('Urbanas', 'Urbanas'), ('Casuales', 'Casuales')], max_length=50, null=True)),
            ],
            options={
                'permissions': (('administrador', 'Es administrador'), ('cliente', 'Es cliente')),
            },
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('rut', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=12)),
                ('contraseña', models.CharField(max_length=20)),
            ],
            options={'permissions': (('administrador', 'Es administrador'), ('cliente', 'Es cliente'))},
        ),
    ]
